version: "3.8"

services:
  water-quality-app:
    build: .
    container_name: water_quality_monitor
    ports:
      - "8501:8501" # Access at http://localhost:8501
    volumes:
      - .:/app # Live reload â€” changes reflect instantly
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
